name = "unicode_text"
description = "SPARK-compatible UTF-8 text operations and bounded strings"
version = "0.6.0"

authors = ["kanig"]
maintainers = ["kanig <kanig@adacore.com>"]
maintainers-logins = ["kanig"]
licenses = "Apache-2.0 WITH LLVM-exception"

project-files = ["unicode_text_lib.gpr"]

[build-switches]
"*".contracts = "Yes"
